---
# tasks file for test_task

- name: zabbix_agent | Add repository
  get_url: 
    url=http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb 
    dest=/tmp/zabbix-release_3.0-1+trusty_all.deb
    validate_certs=no

- name: zabbix_agent | Install deb package
  apt: deb=/tmp/zabbix-release_3.0-1+trusty_all.deb

- name: zabbix_agent | Install zabbix_agent
  apt: pkg=zabbix-agent state=present update_cache=true

- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Server=127.0.0.1" line="Server=172.16.22.252" backrefs=yes
- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^ServerActive=127.0.0.1" line="ServerActive=172.16.22.252" backrefs=yes
- lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Hostname=Zabbix server" line="Hostname=appserver" backrefs=yes
  notify:
    - restart zabbix-agent
